name: 📦 Publish to (Test)PyPI

on:
  push:
    branches: [ main ]          # build + upload to TEST‑PyPI
    tags:     [ 'v*.*.*' ]      # build + upload to real PyPI (semver tags)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      # required by pypa/gh-action-pypi-publish to read the package files
      contents: read

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'   # any supported CPython; the wheel is universal

    - name: Install build backend
      run: |
        python -m pip install --upgrade pip build

    - name: Build sdist & wheel
      run: python -m build -o dist/

    - name: Upload artefacts to workflow run       # handy for manual inspection
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

    # --------------------------------------------------------------
    #  ———  TestPyPI on *every push to main*  ———
    # --------------------------------------------------------------
    - name: Publish to TestPyPI
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        skip-existing: true      # don’t error if we push the same version again

    # --------------------------------------------------------------
    #  ———  Real PyPI on *tagged* pushes (vX.Y.Z)  ———
    # --------------------------------------------------------------
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}